In [1]:
from collections import defaultdict

from jinja2.utils import LRUCache
from sklearn.metrics import accuracy_score

from WhirlwindTourOfPython.website.fabfile import preview

# random string derivation
# represent a BNF as a dictionary

G = {
    "<expr>": [
        ["(", "<expr>", "<biop>", "<expr>", ")"],
        ["<uop>", "<expr>"],
        ["<var>"]
    ],
    "<biop>": [["and"], ["or"]],
    "<uop>": [["not"]],
    "<var>": [["x[0]"], ["x[1]"], ["x[2]"]]
}


import random

def derive_random(G, symbol):
    if symbol in G: #in keys -- non-terminal
        production = random.choice(G[symbol])
        return " ".join(derive_random(G,s) for s in production)
    else:
        return symbol

In [ ]:
# fsm validation

def validate(fsm, start, end_states, seq):
    state = start
    for symbol in seq:
        if symbol not in fsm.get(state, {}):
            return False
        state = fsm[state][symbol] # core transition line
    return state in end_states

In [ ]:
G = {
    "<expr>": [
        ["(", "<expr>", "<biop>", "<expr>", ")"],
        ["<uop>", "<expr>"],
        ["<var>"]
    ],
    "<biop>": [["and"], ["or"]],
    "<uop>": [["not"]],
    "<var>": [["x[0]"], ["x[1]"], ["x[2]"]]
}

def derive_r(G, symbol):
    if symbol in G: # non-terminal
        production = random.choice(G[symbol])
        return " ".join(derive_r(G, s) for s in production)
    else:
        return symbol



In [ ]:
def val_fsm(fsm, start, end_states, sequence):
    state = start
    for s in sequence:
        if s not in fsm.get(start, {}):
            return False
        state = fsm[start][s]
    return state in end_states

In [ ]:
def memo(f):
    cache = {}
    def wrapper(*args):
        if args not in cache:
            cache[args] = f(*args)
        return cache[args]
    return wrapper

In [ ]:
def ran_d(G,symbol):

    if symbol in G:
        production = random.choice(G[symbol])
        return " ".join(ran_d(G, s) for s in production)
    else:
        return symbol





In [ ]:
# state = fsm[state][symbol] -- core transition line

In [ ]:
def memoize(f):
    cache = {}
    def wrapper(*args):
        if args not in cache:
            cache[args] = f(args)
        return cache[args]

    return wrapper


In [ ]:
from functools import lru_cache

@LRUCache
def foo(x):
    return x**2

foo.

In [ ]:
def m(f):
    cache = {}
    def wrapper(*args):
        if args not in cache:
            cache[args] = f(args)
        return cache[args]
    return wrapper

In [ ]:
def fib(n):
    if n <= 1: return n
    return fib(n-1) + fib(n-2)

def memoise_wr(f):
    cache = {}
    def wrapper(*args):
        if not args in cache:
            cache[args] = f(args)
        return cache[args]
    return wrapper




In [5]:
import numpy as np

x = np.array([1,1,2,54,1,2,56,3,7])
s = (np.diff(x) > 0).sum()
s

np.int64(5)

In [ ]:
def d_r(G, symbol):
    if symbol in G:
        production = random.choice(G[symbol])
        return " ".join(d_r(G, s) for s in production)
    else:
        return symbol

In [8]:
L = [1,2,3,4,5]
x = np.array(L)

s = (np.diff(L) > 0).sum()


np.linspace(0, 10, 5, endpoint=False)

array([0., 2., 4., 6., 8.])

In [ ]:
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(X)

score = lin_reg.score()
preds = lin_reg.predict(X)


In [ ]:
s = (np.diff(L) < 0).sum

In [ ]:
from sklearn.base import BaseEstimator, ClassifierMixin, RegressorMixin

class MyClassifer(BaseEstimator, ClassifierMixin):
    def __init__(self, param=1):
        self.param = param

    def fit(self, X, y=None):
        self.X_ = X
        self.Y_ = y
       return self

    def predict(self, X):
       return xs

In [ ]:
class MyObj:
    def __init__(self):
        # super.__init__(self...)
    def __le__(self, other):
        return len(self) <= len(other)

In [ ]:
def read_lines(file):
    for line in open(file):
        yield line.strip()

In [ ]:
class Mine:
    def __init__(self):
        super.__init__()

In [ ]:
def my_reader(file):
    for l in open(file):
        yield l

In [10]:
xs = np.ones(100)

np.diff(xs)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
from collections import defaultdict
defaultdict(lambda: 0)

a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([10, 100])

In [19]:
x = np.linspace(0, 1, 100, endpoint=False)
y = np.random.random((100,))
z = x < y

# z.shape
y

array([0.06902958, 0.16544621, 0.74713522, 0.80551719, 0.90722071,
       0.87111081, 0.55809472, 0.15344534, 0.60624992, 0.79194288,
       0.09438652, 0.63949368, 0.10780235, 0.54224664, 0.62861563,
       0.97095925, 0.02812864, 0.26923855, 0.98656947, 0.21704176,
       0.17035733, 0.33114291, 0.57301644, 0.99805666, 0.01547675,
       0.29944384, 0.93822425, 0.10828411, 0.36325624, 0.3668147 ,
       0.07843294, 0.08155533, 0.35157274, 0.48637682, 0.37326615,
       0.82690338, 0.90529287, 0.87605715, 0.99009237, 0.47897498,
       0.50741668, 0.45959113, 0.47028878, 0.50805568, 0.85750035,
       0.13538676, 0.30024683, 0.3733757 , 0.22619384, 0.643998  ,
       0.70336944, 0.28661833, 0.11487892, 0.19094825, 0.13894181,
       0.58445791, 0.45295818, 0.47436945, 0.14404674, 0.39476836,
       0.2359115 , 0.93711801, 0.32985029, 0.19007026, 0.49833699,
       0.28768962, 0.20021334, 0.77205506, 0.2691959 , 0.5408919 ,
       0.17522647, 0.67139259, 0.91593113, 0.00368908, 0.53691